// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo8ZfWibx3ucI8qnpz9C_80njK7srRHsQ',
    appId: '1:373850671495:web:8d2fbfad7ace55c740eb22',
    messagingSenderId: '373850671495',
    projectId: 'smart-parking-system-bd526',
    authDomain: 'smart-parking-system-bd526.firebaseapp.com',
    databaseURL: 'https://smart-parking-system-bd526-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-parking-system-bd526.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAVaufHiH66ZAUAHwHyZWLOdpzWV0GiUw',
    appId: '1:373850671495:android:a9c842d1d2abcbf640eb22',
    messagingSenderId: '373850671495',
    projectId: 'smart-parking-system-bd526',
    databaseURL: 'https://smart-parking-system-bd526-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-parking-system-bd526.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4DvB4aInX8-eXagh9lBoONnSXMkpafb0',
    appId: '1:373850671495:ios:962bdd33b8ff7d8040eb22',
    messagingSenderId: '373850671495',
    projectId: 'smart-parking-system-bd526',
    databaseURL: 'https://smart-parking-system-bd526-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-parking-system-bd526.firebasestorage.app',
    iosBundleId: 'com.example.parkingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4DvB4aInX8-eXagh9lBoONnSXMkpafb0',
    appId: '1:373850671495:ios:962bdd33b8ff7d8040eb22',
    messagingSenderId: '373850671495',
    projectId: 'smart-parking-system-bd526',
    databaseURL: 'https://smart-parking-system-bd526-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-parking-system-bd526.firebasestorage.app',
    iosBundleId: 'com.example.parkingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo8ZfWibx3ucI8qnpz9C_80njK7srRHsQ',
    appId: '1:373850671495:web:6a33f0aa8ccb782e40eb22',
    messagingSenderId: '373850671495',
    projectId: 'smart-parking-system-bd526',
    authDomain: 'smart-parking-system-bd526.firebaseapp.com',
    databaseURL: 'https://smart-parking-system-bd526-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-parking-system-bd526.firebasestorage.app',
  );
}
